In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("C:/Users/vidhy/OneDrive/Pictures/Documents/train_data.csv")
df

     Unnamed: 0  PassengerId  Survived  Sex  ...  Title_4  Emb_1  Emb_2  Emb_3
0             0            1         0    1  ...        0      0      0      1
1             1            2         1    0  ...        0      1      0      0
2             2            3         1    0  ...        1      0      0      1
3             3            4         1    0  ...        0      0      0      1
4             4            5         0    1  ...        0      0      0      1
..          ...          ...       ...  ...  ...      ...    ...    ...    ...
787         787          788         0    1  ...        0      0      1      0
788         788          789         1    1  ...        0      0      0      1
789         789          790         0    1  ...        0      1      0      0
790         790          791         0    1  ...        0      0      1      0
791         791          792         0    1  ...        0      0      0      1

[792 rows x 17 columns]

In [3]:
df.shape

(792, 17)

In [4]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Sex', 'Age', 'Fare',
       'Pclass_1', 'Pclass_2', 'Pclass_3', 'Family_size', 'Title_1', 'Title_2',
       'Title_3', 'Title_4', 'Emb_1', 'Emb_2', 'Emb_3'],
      dtype='object')

In [5]:
df.head()

   Unnamed: 0  PassengerId  Survived  Sex  ...  Title_4  Emb_1  Emb_2  Emb_3
0           0            1         0    1  ...        0      0      0      1
1           1            2         1    0  ...        0      1      0      0
2           2            3         1    0  ...        1      0      0      1
3           3            4         1    0  ...        0      0      0      1
4           4            5         0    1  ...        0      0      0      1

[5 rows x 17 columns]

In [6]:
df.tail()

     Unnamed: 0  PassengerId  Survived  Sex  ...  Title_4  Emb_1  Emb_2  Emb_3
787         787          788         0    1  ...        0      0      1      0
788         788          789         1    1  ...        0      0      0      1
789         789          790         0    1  ...        0      1      0      0
790         790          791         0    1  ...        0      0      1      0
791         791          792         0    1  ...        0      0      0      1

[5 rows x 17 columns]

In [7]:
df.dtypes

Unnamed: 0       int64
PassengerId      int64
Survived         int64
Sex              int64
Age            float64
Fare           float64
Pclass_1         int64
Pclass_2         int64
Pclass_3         int64
Family_size    float64
Title_1          int64
Title_2          int64
Title_3          int64
Title_4          int64
Emb_1            int64
Emb_2            int64
Emb_3            int64
dtype: object

In [8]:
df.isna().sum()

Unnamed: 0     0
PassengerId    0
Survived       0
Sex            0
Age            0
Fare           0
Pclass_1       0
Pclass_2       0
Pclass_3       0
Family_size    0
Title_1        0
Title_2        0
Title_3        0
Title_4        0
Emb_1          0
Emb_2          0
Emb_3          0
dtype: int64

In [9]:
df.drop(['Unnamed: 0','PassengerId'], axis=1,inplace=True)

In [10]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
787    0
788    1
789    0
790    0
791    0
Name: Survived, Length: 792, dtype: int64

In [11]:
dft=pd.read_csv("C:/Users/vidhy/OneDrive/Pictures/Documents/test_data.csv")
dft

    Unnamed: 0  PassengerId  Survived  Sex  ...  Title_4  Emb_1  Emb_2  Emb_3
0          791          792         0    1  ...        0      0      0      1
1          792          793         0    0  ...        1      0      0      1
2          793          794         0    1  ...        0      1      0      0
3          794          795         0    1  ...        0      0      0      1
4          795          796         0    1  ...        0      0      0      1
..         ...          ...       ...  ...  ...      ...    ...    ...    ...
95         886          887         0    1  ...        0      0      0      1
96         887          888         1    0  ...        1      0      0      1
97         888          889         0    0  ...        1      0      0      1
98         889          890         1    1  ...        0      1      0      0
99         890          891         0    1  ...        0      0      1      0

[100 rows x 17 columns]

In [12]:
dft.shape

(100, 17)

In [13]:
dft.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Sex', 'Age', 'Fare',
       'Pclass_1', 'Pclass_2', 'Pclass_3', 'Family_size', 'Title_1', 'Title_2',
       'Title_3', 'Title_4', 'Emb_1', 'Emb_2', 'Emb_3'],
      dtype='object')

In [14]:
dft.head()

   Unnamed: 0  PassengerId  Survived  Sex  ...  Title_4  Emb_1  Emb_2  Emb_3
0         791          792         0    1  ...        0      0      0      1
1         792          793         0    0  ...        1      0      0      1
2         793          794         0    1  ...        0      1      0      0
3         794          795         0    1  ...        0      0      0      1
4         795          796         0    1  ...        0      0      0      1

[5 rows x 17 columns]

In [15]:
dft.tail()

    Unnamed: 0  PassengerId  Survived  Sex  ...  Title_4  Emb_1  Emb_2  Emb_3
95         886          887         0    1  ...        0      0      0      1
96         887          888         1    0  ...        1      0      0      1
97         888          889         0    0  ...        1      0      0      1
98         889          890         1    1  ...        0      1      0      0
99         890          891         0    1  ...        0      0      1      0

[5 rows x 17 columns]

In [16]:
dft.dtypes

Unnamed: 0       int64
PassengerId      int64
Survived         int64
Sex              int64
Age            float64
Fare           float64
Pclass_1         int64
Pclass_2         int64
Pclass_3         int64
Family_size    float64
Title_1          int64
Title_2          int64
Title_3          int64
Title_4          int64
Emb_1            int64
Emb_2            int64
Emb_3            int64
dtype: object

In [17]:
dft.isna().sum()

Unnamed: 0     0
PassengerId    0
Survived       0
Sex            0
Age            0
Fare           0
Pclass_1       0
Pclass_2       0
Pclass_3       0
Family_size    0
Title_1        0
Title_2        0
Title_3        0
Title_4        0
Emb_1          0
Emb_2          0
Emb_3          0
dtype: int64

In [18]:
dft.drop(['Unnamed: 0','PassengerId'], axis=1,inplace=True)

In [19]:
df.shape

(792, 15)

In [20]:
dft.shape

(100, 15)

In [21]:
a=dft.drop(['Survived'],axis=1)
b=dft['Survived']

In [22]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=7)
model.fit(x,y)
y_pred=model.predict(a)
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(b,y_pred)
cm

array([[54, 10],
       [ 8, 28]])

In [27]:
score=accuracy_score(b,y_pred)*100
score

82.0

0.21875