In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("C:/Users/vidhy/OneDrive/Pictures/Documents/winequality-red.csv")
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [86]:
df.shape

(1599, 12)

In [87]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [88]:
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [89]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [90]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [91]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [92]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]],
      shape=(1599, 11))

In [93]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[ 8.6 ,  0.22,  0.36, ...,  3.47,  0.87, 11.  ],
       [12.5 ,  0.46,  0.63, ...,  2.99,  0.87, 10.2 ],
       [ 7.2 ,  0.54,  0.27, ...,  3.39,  0.71, 11.  ],
       ...,
       [ 7.2 ,  0.62,  0.06, ...,  3.51,  0.54,  9.5 ],
       [ 7.9 ,  0.2 ,  0.35, ...,  3.32,  0.8 , 11.9 ],
       [ 5.8 ,  0.29,  0.26, ...,  3.39,  0.54, 13.5 ]], shape=(1119, 11))

In [94]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [95]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 7, 6, 6, 5, 6, 7, 5, 5, 7, 5, 5, 6,
       5, 6, 5, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6, 5,
       6, 6, 7, 6, 5, 5, 5, 5, 6, 7, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 7, 5,
       6, 6, 7, 5, 6, 6, 6, 6, 6, 5, 7, 6, 6, 7, 5, 7, 5, 5, 6, 6, 5, 6,
       7, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5,
       7, 5, 6, 5, 5, 6, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6, 5,
       5, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 6, 5, 5,
       6, 6, 5, 6, 5, 6, 7, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 5, 6,
       6, 5, 6, 5, 5, 7, 6, 7, 5, 6, 6, 6, 7, 5, 6, 6, 5, 7, 6, 5, 5, 6,
       5, 6, 6, 5, 5, 5, 7, 6, 5, 5, 5, 5, 7, 5, 6, 6, 6, 6, 6, 5, 6, 6,
       5, 6, 6, 6, 6, 5, 6, 7, 6, 5, 6, 4, 7, 6, 5, 6, 5, 6, 6, 5, 5, 5,
       6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 4, 6, 7, 7, 6, 5, 7,
       6, 7, 6, 5, 5, 7, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 7, 6, 5, 5, 5, 6,
       5, 6, 6, 6, 5, 7, 5, 6, 5, 6, 5, 7, 7, 7, 6, 5, 6, 5, 6, 5, 6, 6,
       6, 7, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 6, 5, 3, 5, 6, 6, 5, 6,
       6, 7, 5, 5, 6, 6, 5, 6, 5, 6, 6, 7, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6,
       5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6,
       6, 6, 6, 7, 5, 5, 5, 7, 7, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 6, 6,
       7, 5, 6, 7, 5, 5, 6, 5, 5, 6, 5, 7, 5, 5, 6, 7, 5, 6, 6, 7, 6, 7,
       5, 6, 7, 5, 6, 6, 5, 5, 5, 5, 6, 5, 7, 6, 5, 5, 6, 5, 5, 5, 5, 6,
       6, 6, 7, 5, 6, 5, 5, 6, 5, 5, 7, 5, 5, 5, 5, 6, 7, 6, 5, 5, 5, 6,
       5, 5, 6, 5, 6, 6, 6, 7, 7, 6, 6, 6, 5, 6, 6, 6, 7, 5])

In [96]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[  0,   0,   0,   1,   0,   0],
       [  0,   0,   9,   8,   0,   0],
       [  1,   1, 136,  53,   4,   0],
       [  0,   1,  67, 113,  19,   0],
       [  0,   0,   9,  27,  25,   0],
       [  0,   0,   1,   1,   4,   0]])

In [97]:
score=accuracy_score(y_test,y_pred)
score

0.5708333333333333

In [98]:
from sklearn.model_selection import GridSearchCV
model1=KNeighborsClassifier()
data={'n_neighbors':[3,5,7,9,11],'weights':['uniform','distance'],'metric':['euclidean','manhattan'],'algorithm':['ball_tree','kd_tree','brute']}
clf=GridSearchCV(model1,data,cv=10,scoring='accuracy')
clf.fit(x_train,y_train)

C:\Users\vidhy\AppData\Roaming\Python\Python311\site-packages\sklearn\model_selection\_split.py:813: UserWarning: The least populated class in y has only 9 members, which is less than n_splits=10.
  warnings.warn(

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [99]:
print(clf.best_params_)

{'algorithm': 'ball_tree', 'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'distance'}

In [102]:
model2=KNeighborsClassifier(n_neighbors=7,algorithm='ball_tree',metric= 'euclidean',weights='distance')
model2.fit(x_train,y_train)
y_pred1=model2.predict(x_test)
y_pred1

array([5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 7, 6, 6, 5, 6, 7, 5, 5, 7, 5, 5, 6,
       5, 6, 5, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 7, 5,
       6, 6, 7, 6, 5, 5, 5, 5, 6, 7, 5, 6, 6, 5, 6, 5, 6, 6, 6, 5, 7, 5,
       6, 6, 7, 6, 6, 6, 6, 6, 6, 5, 7, 5, 6, 7, 5, 7, 5, 6, 6, 6, 5, 6,
       7, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 7, 6, 5, 5, 5,
       7, 5, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 6, 6, 5,
       5, 6, 5, 5, 5, 5, 5, 5, 7, 6, 7, 6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5,
       6, 5, 5, 6, 5, 6, 7, 6, 6, 6, 5, 6, 6, 5, 5, 5, 5, 5, 7, 5, 7, 6,
       6, 5, 5, 5, 5, 6, 6, 7, 5, 6, 6, 6, 7, 5, 6, 6, 5, 7, 6, 5, 5, 6,
       5, 7, 5, 5, 5, 5, 7, 6, 5, 5, 5, 6, 8, 5, 5, 6, 6, 6, 6, 5, 6, 6,
       6, 6, 7, 6, 6, 5, 6, 7, 5, 5, 6, 5, 7, 6, 5, 7, 5, 6, 6, 5, 5, 5,
       6, 7, 5, 7, 5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 7, 6, 5, 7,
       6, 7, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 7, 6, 5, 6, 6, 7,
       5, 6, 6, 6, 5, 6, 6, 6, 5, 6, 5, 7, 7, 7, 5, 5, 7, 5, 6, 6, 6, 6,
       6, 7, 6, 6, 6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6,
       6, 7, 5, 6, 6, 6, 5, 6, 5, 6, 6, 7, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 6, 5, 7, 6, 5, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 6,
       6, 6, 6, 7, 5, 6, 5, 7, 7, 6, 7, 7, 7, 5, 6, 6, 5, 5, 5, 6, 6, 6,
       7, 5, 6, 7, 5, 5, 6, 5, 6, 6, 7, 6, 6, 5, 6, 7, 6, 6, 5, 6, 6, 7,
       6, 7, 7, 5, 6, 6, 5, 6, 5, 5, 6, 5, 7, 6, 5, 5, 7, 5, 5, 5, 5, 6,
       6, 6, 7, 5, 6, 5, 5, 5, 6, 5, 7, 5, 5, 5, 5, 6, 7, 6, 6, 5, 5, 6,
       5, 5, 6, 5, 6, 6, 5, 6, 7, 6, 6, 6, 5, 7, 8, 6, 7, 5])

In [103]:
score=accuracy_score(y_test,y_pred1)*100
score

64.16666666666667